ERP/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app_dashboard.urls')),
    path('produtos/', include('app_produtos.urls')),
    path('clientes/', include('app_clientes.urls')),
    path('fornecedores/', include('app_fornecedores.urls')),
    path('pagamentos/', include('app_pagamentos.urls')),
    path('recebimentos/', include('app_recebimentos.urls')),
    path('empresas/', include('app_empresas.urls')),
    path('usuarios/', include('app_usuarios.urls')),
    path('login/', include('app_login.urls')),
    path('pedidos/', include('app_pedidos.urls')),
    path('api/', include('api.urls'))
]

app_fornecedores/urls.py
from django.urls import path
from app_fornecedores import views

app_name = 'fornecedores'

urlpatterns = [
    path('', views.fornecedores_view, name='fornecedores'),
    path('adicionar', views.adicionar_fornecedor, name='adicionar_fornecedor'),
    path('editar/<fornecedor_id>', views.editar_fornecedor, name='editar_fornecedor'),
    path('deletar/<fornecedor_id>', views.delete_fornecedor, name='deletar_fornecedor'),
]

app_fornecedores/models.py
from django.db import models
from app_empresas.models import Empresa

class Fornecedor(models.Model):
    empresa = models.ForeignKey(Empresa, on_delete=models.CASCADE, verbose_name='Empresa')
    nome = models.CharField(max_length=120, verbose_name='Nome')
    telefone = models.CharField(max_length=20, verbose_name='Telefone')
    documento = models.CharField(max_length=20, verbose_name='CPF/CNPJ')
    rua = models.CharField(max_length=250, verbose_name='Logradouro')
    numero = models.CharField(max_length=10, verbose_name='Número')
    bairro = models.CharField(max_length=100, verbose_name='Bairro')
    cidade = models.CharField(max_length=100, verbose_name='Cidade')
    estado = models.CharField(max_length=2, verbose_name='Estado')

    def __str__(self):
        return self.nome

app_fornecedores/forms.py
from django import forms
from app_fornecedores.models import Fornecedor

class FornecedorForm(forms.ModelForm):

    class Meta:
        model = Fornecedor
        fields = [
            'empresa',
            'nome',
            'telefone',
            'documento',
            'rua',
            'numero',
            'bairro',
            'cidade',
            'estado'
        ]
    
    def __init__(self, request, *args, **kwargs):
        super(FornecedorForm, self).__init__(*args, **kwargs)
        if not request.user.is_staff:
            del self.fields['empresa']

class EditFornecedorForm(forms.ModelForm):

    class Meta:
        model = Fornecedor
        fields = [
            'nome',
            'telefone',
            'documento',
            'rua',
            'numero',
            'bairro',
            'cidade',
            'estado'
        ]

app_fornecedores/views.py
from django.shortcuts import render, redirect, get_object_or_404
from app_fornecedores.models import Fornecedor
from app_fornecedores.forms import FornecedorForm, EditFornecedorForm
from app_fornecedores.tables import FornecedorTable
from django.contrib import messages
from django.contrib.auth.decorators import login_required

@login_required(login_url='login:login', redirect_field_name='next')
def fornecedores_view(request):
    if request.user.is_staff:
        fornecedores = Fornecedor.objects.all()
    else:
        fornecedores = Fornecedor.objects.filter(empresa=request.user.empresa)
    table = FornecedorTable(fornecedores)
    return render(request, 'pages/fornecedores.html', context={
        'title': 'Fornecedores',
        'table': table,
    })

@login_required(login_url='login:login', redirect_field_name='next')
def adicionar_fornecedor(request):
    if request.method == 'POST':
        form = FornecedorForm(request, request.POST)
        if form.is_valid():
            novo_fornecedor = form.save(commit=False)
            novo_fornecedor.empresa = form.cleaned_data.get('empresa', request.user.empresa)
            form.save()
            messages.success(request, f'O fornecedor "{novo_fornecedor.nome}" foi adicionado com sucesso!')
            return redirect ('fornecedores:fornecedores')
    else:
        form = FornecedorForm(request)

    return render (request, 'pages/adicionar_fornecedor.html', context={
        'title': 'Adicionar fornecedor',
        'form': form
    })

@login_required(login_url='login:login', redirect_field_name='next')
def editar_fornecedor(request, fornecedor_id):
    fornecedor = get_object_or_404(Fornecedor, pk=fornecedor_id)
    if request.method == 'POST':
        form = EditFornecedorForm(request.POST, instance=fornecedor)
        if form.is_valid():
            fornecedor_edit = form.save()
            messages.success(request, f'O fornecedor "{fornecedor_edit.nome}" foi editado com sucesso!')
            return redirect('fornecedores:fornecedores')
    else:
        form = EditFornecedorForm(instance=fornecedor)

    return render (request, 'pages/adicionar_fornecedor.html', context={
        'title': 'Editar fornecedor',
        'form': form
    })

@login_required(login_url='login:login', redirect_field_name='next')
def delete_fornecedor(request, fornecedor_id):
    fornecedor = get_object_or_404(Fornecedor, pk=fornecedor_id)
    
    fornecedor.delete()
    messages.success(request, f'O fornecedor foi deletado com sucesso!')
    return redirect('fornecedores:fornecedores')

app_fornecedores/templates/pages/adicionar_fornecedor.html
{% extends "global/index.html" %}
{% load bootstrap5 %}

{% block content %}
    <a href="{% url "fornecedores:fornecedores" %}" class="btn btn-primary mb-3">
        <span class="fas fa-arrow-left mr-1"></span>
        Voltar
    </a>
    <div class="card">
        <div class="card-body">
            <form method="post">
                {% csrf_token %}
                {% bootstrap_form form %}
                <button type="submit" class="btn btn-primary">
                    <span class="fas fa-save"></span>
                    Salvar
                </button>
            </form>
        </div>
    </div>
{% endblock content %}

app_fornecedores/templates/pages/botao_acoes_fornecedores.html
<div class="dropdown">
    <button class="btn btn-dark btn-sm dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
        Opções
    </button>
    <div class="dropdown-menu">
        <a class="dropdown-item" href="{% url "fornecedores:editar_fornecedor" record.id %}">Editar</a>
        <a class="dropdown-item" href="{% url "fornecedores:deletar_fornecedor" record.id %}">Deletar</a>
    </div>
</div>

app_fornecedores/templates/pages/fornecedores.html
{% extends "global/index.html" %}
{% load render_table from django_tables2 %}

{% block content %}
<a href="{% url "fornecedores:adicionar_fornecedor" %}" class="btn btn-primary mb-3">
    <span class="fas fa-plus mr-1"></span>
    Cadastrar
</a>
<div class="card">
    <div class="card-body">
        <table class="table table-bordered table-hover">
            {% render_table table %}
        </table>
    </div>
</div>
{% endblock content %}