ERP/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app_dashboard.urls')),
    path('produtos/', include('app_produtos.urls')),
    path('clientes/', include('app_clientes.urls')),
    path('fornecedores/', include('app_fornecedores.urls')),
    path('pagamentos/', include('app_pagamentos.urls')),
    path('recebimentos/', include('app_recebimentos.urls')),
    path('empresas/', include('app_empresas.urls')),
    path('usuarios/', include('app_usuarios.urls')),
    path('login/', include('app_login.urls')),
    path('pedidos/', include('app_pedidos.urls')),
    path('api/', include('api.urls'))
]

app_pagamentos/urls.py
from django.urls import path
from app_pagamentos import views

app_name = 'pagamentos'

urlpatterns = [
    path('', views.pagamentos_views, name='pagamentos'),
    path('adicionar/', views.adicionar_pagamento, name='adicionar_pagamento'),
    path('editar/<pagamento_id>', views.editar_pagamento, name='editar_pagamento'),
    path('deletar/<pagamento_id>', views.delete_pagamento, name='delete_pagamento'),
]

app_pagamentos/models.py
from django.db import models
from app_fornecedores.models import Fornecedor
from app_empresas.models import Empresa

PAGAMENTO_STATUS = [
    ('pendente', 'Pendente'),
    ('pago', 'Pago'),
    ('cancelado', 'Cancelado'),
]

class Pagamento(models.Model):
    empresa = models.ForeignKey(Empresa, on_delete=models.CASCADE, verbose_name='Empresa')
    fornecedor = models.ForeignKey(Fornecedor, on_delete=models.CASCADE)
    descricao = models.CharField(max_length=255, verbose_name='Descrição')
    valor = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='Valor')
    data_emissao = models.DateField(auto_now_add=True, verbose_name='Data de Emissão')
    data_vencimento = models.DateField(verbose_name='Data de Vencimento')
    status = models.CharField(max_length=30, choices=PAGAMENTO_STATUS, default='pendente')

    def __str__(self):
        return self.fornecedor.nome

app_pagamentos/forms.py
from django import forms
from app_pagamentos.models import Pagamento

class PagamentoForm(forms.ModelForm):

    class Meta:
        model = Pagamento
        fields = [
            'empresa',
            'fornecedor',
            'descricao',
            'valor',
            'data_vencimento',
            'status',
        ]
        widgets = {
            'data_vencimento': forms.widgets.DateInput(attrs={'type': 'date'})
        }
    
    def __init__(self, request, *args, **kwargs):
        super(PagamentoForm, self).__init__(*args, **kwargs)
        if not request.user.is_staff:
            del self.fields['empresa']

class EditPagamentoForm(forms.ModelForm):

    class Meta:
        model = Pagamento
        fields = [
            'fornecedor',
            'descricao',
            'valor',
            'data_vencimento',
            'status',
        ]
        widgets = {
            'data_vencimento': forms.widgets.DateInput(attrs={'type': 'date'})
        }

app_pagamentos/views.py
from django.shortcuts import render, redirect, get_object_or_404
from app_pagamentos.models import Pagamento
from app_pagamentos.forms import PagamentoForm, EditPagamentoForm
from django.contrib import messages
from app_pagamentos.tables import PagamentoTable
from django.contrib.auth.decorators import login_required

@login_required(login_url='login:login', redirect_field_name='next')
def pagamentos_views(request):
    if request.user.is_staff:
        pagamentos = Pagamento.objects.all()
    else:
        pagamentos = Pagamento.objects.filter(empresa=request.user.empresa)
    table = PagamentoTable(pagamentos)
    return render(request, 'pages/pagamentos.html', context={
        'title': 'Pagamentos',
        'table': table
    })

@login_required(login_url='login:login', redirect_field_name='next')
def adicionar_pagamento(request):
    if request.method == 'POST':
        form = PagamentoForm(request, request.POST)
        if form.is_valid():
            novo_pagamento = form.save(commit=False)
            novo_pagamento.empresa = form.cleaned_data.get('empresa', request.user.empresa)
            form.save()
            messages.success(request, f'O pagamento do fornecedor "{novo_pagamento.fornecedor.nome}" foi adicionado com sucesso!')
            return redirect('pagamentos:pagamentos')
    else:
        form = PagamentoForm(request)

    return render(request, 'pages/adicionar_pagamento.html', context={
        'title': 'Adicionar pagamento',
        'form': form, 
    })

@login_required(login_url='login:login', redirect_field_name='next')
def editar_pagamento(request, pagamento_id):
    pagamento = get_object_or_404(Pagamento, pk=pagamento_id)
    if request.method == 'POST':
        form = EditPagamentoForm(request.POST, instance=pagamento)
        if form.is_valid():
            pagamento_edit = form.save()
            messages.success(request, f'O pagamento do fornecedor "{pagamento_edit.fornecedor.nome}" foi editado com sucesso!')
            return redirect('pagamentos:pagamentos')
    else:
        form = EditPagamentoForm(instance=pagamento)

    return render(request, 'pages/adicionar_pagamento.html', context={
        'title': 'Editar pagamento',
        'form': form,
        'pagamento': pagamento
    })

@login_required(login_url='login:login', redirect_field_name='next')
def delete_pagamento(request, pagamento_id):
    pagamento = get_object_or_404(Pagamento, pk=pagamento_id)

    pagamento.delete()
    messages.success(request, 'O pagamento foi deletado com sucesso!')
    return redirect('pagamentos:pagamentos')

app_pagamentos/templates/pages/adicionar_pagamento.html
{% extends "global/index.html" %}
{% load bootstrap5 %}

{% block content %}
    <a href="{% url "pagamentos:pagamentos" %}" class="btn btn-primary mb-3">
        <span class="fas fa-arrow-left mr-1"></span>
        Voltar
    </a>
    <div class="card">
        <div class="card-body">
            <form method="post">
                {% csrf_token %}
                {% bootstrap_form form %}
                <button type="submit" class="btn btn-primary">
                    <span class="fas fa-save"></span>
                    Salvar
                </button>
            </form>
        </div>
    </div>
{% endblock content %}

app_pagamentos/templates/pages/botao_acoes.html
<div class="dropdown">
    <button class="btn btn-dark btn-sm dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
        Opções
    </button>
    <div class="dropdown-menu">
        <a class="dropdown-item" href="{% url "pagamentos:editar_pagamento" record.id %}">Editar</a>
        <a class="dropdown-item" href="{% url "pagamentos:delete_pagamento" record.id %}">Deletar</a>
    </div>
</div>

app_pagamentos/templates/pages/pagamentos.html
{% extends "global/index.html" %}
{% load render_table from django_tables2 %}


{% block content %}
<a href="{% url "pagamentos:adicionar_pagamento" %}" class="btn btn-primary mb-3">
    <span class="fas fa-plus mr-1"></span>
    Cadastrar
</a>
<div class="card">
    <div class="card-body">
        <table class="table table-bordered table-hover">
            {% render_table table %}
        </table>
    </div>
</div>
{% endblock content %}