ERP/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app_dashboard.urls')),
    path('produtos/', include('app_produtos.urls')),
    path('clientes/', include('app_clientes.urls')),
    path('fornecedores/', include('app_fornecedores.urls')),
    path('pagamentos/', include('app_pagamentos.urls')),
    path('recebimentos/', include('app_recebimentos.urls')),
    path('empresas/', include('app_empresas.urls')),
    path('usuarios/', include('app_usuarios.urls')),
    path('login/', include('app_login.urls')),
    path('pedidos/', include('app_pedidos.urls')),
    path('api/', include('api.urls'))
]

app_clientes/urls.py
from django.urls import path
from app_clientes import views

app_name = 'clientes'

urlpatterns = [
    path('', views.clientes_views, name='clientes'),
    path('adicionar/', views.adicionar_cliente, name='adicionar_cliente'),
    path('editar/<cliente_id>', views.editar_cliente, name='editar_cliente'),
    path('deletar/<cliente_id>', views.deletar_cliente, name='deletar_cliente')
]

app_clientes/models.py
from django.db import models
from app_empresas.models import Empresa

class Cliente(models.Model):
    empresa = models.ForeignKey(Empresa, verbose_name=('Empresa'), on_delete=models.CASCADE)
    razao_social = models.CharField(max_length=150, verbose_name='Razão social')
    nome_fantasia = models.CharField(max_length=150, null=True,verbose_name='Nome fantasia')
    rg = models.CharField(max_length=9, null=True, blank=True, verbose_name='RG')
    cnpj = models.CharField(max_length=14, null=True, blank=True, verbose_name='CNPJ')
    rua = models.CharField(max_length=50, verbose_name='Rua')
    numero = models.CharField(max_length=5, verbose_name='Numero')
    bairro = models.CharField(max_length=50, verbose_name='Bairro')
    cidade = models.CharField(max_length=50, verbose_name='Cidade')
    estado = models.CharField(max_length=2, verbose_name='Estado')
    cep = models.CharField(max_length=8, verbose_name='CEP')
    complemento = models.CharField(max_length=100, blank=True, verbose_name='Complemento')
    telefone = models.CharField(max_length=11, verbose_name='Telefone')
    telefone_fixo = models.CharField(max_length=11, blank=True, verbose_name='Telefone fixo')

    def __str__(self):
        return self.nome_fantasia

app_clientes/forms.py
from django import forms
from app_clientes.models import Cliente

class ClienteForm(forms.ModelForm):
    class Meta:
        model = Cliente
        fields = [
            'empresa',
            'razao_social',
            'nome_fantasia',
            'rg',
            'cnpj',
            'rua',
            'numero',
            'bairro',
            'cidade',
            'estado',
            'cep',
            'complemento',
            'telefone',
            'telefone_fixo',
        ]

    def __init__(self, request, *args, **kwargs):
        super(ClienteForm, self).__init__(*args, **kwargs)
        if not request.user.is_staff:
            del self.fields['empresa']

class EditClienteForm(forms.ModelForm):

    class Meta:
        model = Cliente
        fields = [
            'razao_social',
            'nome_fantasia',
            'rg',
            'cnpj',
            'rua',
            'numero',
            'bairro',
            'cidade',
            'estado',
            'cep',
            'complemento',
            'telefone',
            'telefone_fixo',
        ]

app_clientes/views.py
from django.shortcuts import render, redirect, get_object_or_404
from app_clientes.models import Cliente
from app_clientes.forms import ClienteForm, EditClienteForm
from app_clientes.tables import ClienteTable
from django.contrib import messages
from django.contrib.auth.decorators import login_required

@login_required(login_url='login:login', redirect_field_name='next')
def clientes_views(resquest):
    if resquest.user.is_staff:
        clientes = Cliente.objects.all()
    else:
        clientes = Cliente.objects.filter(empresa=resquest.user.empresa)
    table = ClienteTable(clientes)
    return render (resquest, 'pages/clientes.html', context= {
        'title': 'Clientes',
        'table': table,
    })

@login_required(login_url='login:login', redirect_field_name='next')
def adicionar_cliente(request):
    if request.method == 'POST':
        form = ClienteForm(request, request.POST)
        if form.is_valid():
            novo_cliente = form.save(commit=False)
            novo_cliente.empresa = form.cleaned_data.get('empresa', request.user.empresa)
            form.save()
            messages.success(request, f"O cliente '{novo_cliente.razao_social}' foi cadastrado com sucesso!")
            return redirect ('clientes:clientes')
    else:
        form = ClienteForm(request)

    return render (request, 'pages/adicionar_cliente.html', context= {
        'title': 'Adicionar cliente',
        'form': form,
    })

@login_required(login_url='login:login', redirect_field_name='next')
def editar_cliente(request, cliente_id):
    cliente = get_object_or_404(Cliente, pk=cliente_id)

    if request.method == 'POST':
        form = EditClienteForm(request.POST, instance=cliente)
        if form.is_valid():
            edit_cliente = form.save()
            messages.success(request, f"O cliente '{edit_cliente.razao_social}' foi editado com sucesso!")
            return redirect ('clientes:clientes')
    else:
        form = EditClienteForm(instance=cliente)
    
    return render (request, 'pages/adicionar_cliente.html', context={
        'title': 'Editar cliente',
        'form': form
    })

@login_required(login_url='login:login', redirect_field_name='next')
def deletar_cliente(request, cliente_id):
    cliente = get_object_or_404(Cliente, pk=cliente_id)

    cliente.delete()
    messages.success(request, 'O cliente foi deletado com sucesso!')
    return redirect('clientes:clientes')
    

app_clientes/templates/pages/adicionar_cliente.html
{% extends "global/index.html" %}
{% load bootstrap5 %}


{% block content %}
    <a href="{% url "clientes:clientes" %}" class="btn btn-primary mb-3">
        <span class="fas fa-arrow-left mr-1"></span>
        Voltar
    </a>
    <div class="card">
        <div class="card-body">
            <form method="post">
                {% csrf_token %}
                {% bootstrap_form form %}
                <button type="submit" class="btn btn-primary">
                    <span class="fas fa-save"></span>
                    Salvar
                </button>
            </form>
        </div>
    </div>
{% endblock content %}

app_clientes/templates/pages/botao_opcoes_clientes.html
<div class="dropdown">
    <button class="btn btn-dark btn-sm dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
        Opções
    </button>
    <div class="dropdown-menu">
        <a class="dropdown-item" href="{% url "clientes:editar_cliente" record.id %}">Editar</a>
        <a class="dropdown-item" href="{% url "clientes:deletar_cliente" record.id %}">Deletar</a>
    </div>
</div>

app_clientes/templates/pages/clientes.html
{% extends "global/index.html" %}
{% load render_table from django_tables2 %}

{% block content %}
    <a href="{% url "clientes:adicionar_cliente" %}" class="btn btn-primary mb-3">
        <span class="fas fa-plus mr-1"></span>
        Cadastrar
    </a>
        <div class="card">
            <div class="card-body">
                <table class="table table-bordered table-hover">
                    {% render_table table %}
                </table>
            </div>
        </div>
{% endblock content %}