ERP/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app_dashboard.urls')),
    path('produtos/', include('app_produtos.urls')),
    path('clientes/', include('app_clientes.urls')),
    path('fornecedores/', include('app_fornecedores.urls')),
    path('pagamentos/', include('app_pagamentos.urls')),
    path('recebimentos/', include('app_recebimentos.urls')),
    path('empresas/', include('app_empresas.urls')),
    path('usuarios/', include('app_usuarios.urls')),
    path('login/', include('app_login.urls')),
    path('pedidos/', include('app_pedidos.urls')),
    path('api/', include('api.urls'))
]

app_usuarios/urls.py
from django.urls import path
from app_usuarios import views

app_name = 'usuarios'

urlpatterns = [
    path('', views.usuarios_view, name='usuarios'),
    path('adicionar/', views.adicionar_usuario, name='adicionar_usuario'),
    path('editar/<usuario_id>/', views.editar_usuario, name='editar_usuario'),
    path('editar/password/<usuario_id>/', views.editar_senha_usuario, name='editar_password'),
    path('deletar/<usuario_id>', views.deletar_usuario, name='deletar_usuario')
]

app_usuarios/models.py
from django.db import models
from app_empresas.models import Empresa
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin

class CustomUserManager(BaseUserManager):
    def create_user(self, email, password=None, **extra_fields):
        if not email:
            raise ValueError('O email é obrigatório!')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self.db)
        return user
    
    def create_admin(self, email, password=None, **extra_fields):
        return self.create_user(email, password, **extra_fields)
    
    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        return self.create_user(email, password, **extra_fields)
    
class CustomUser(AbstractBaseUser, PermissionsMixin):
    empresa = models.ForeignKey(Empresa, verbose_name='Empresa', on_delete=models.CASCADE)
    email = models.EmailField(unique=True)
    nome =  models.CharField(max_length=100)
    is_admin = models.BooleanField(default=False, verbose_name='Admin')
    is_comum = models.BooleanField(default=True, verbose_name='Comum')
    is_staff = models.BooleanField(default=False, verbose_name='Staff')
    date_joined = models.DateTimeField(auto_now_add=True)

    objects = CustomUserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS =  ['nome']

    def __str__(self):
        return self.nome

app_usuarios/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from app_usuarios.models import CustomUser

class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = CustomUser
        fields = [
            'empresa',
            'email',
            'nome',
            'is_admin',
            'is_comum',
        ]

    def __init__(self, request, *args, **kwargs):
        super(CustomUserCreationForm, self).__init__(*args, **kwargs)
        if not request.user.is_staff:
            del self.fields['empresa']
class EditCustomUserCreationForm(UserChangeForm):
    class Meta:
        model = CustomUser
        fields = [
            'email',
            'nome',
            'is_admin',
            'is_comum',
        ]
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        del self.fields['password']

class EditPasswordCustomUserForm(UserChangeForm):
    class Meta:
        model = CustomUser
        fields = [
            'password'
        ]

app_usuarios/views.py
from django.shortcuts import render, redirect, get_object_or_404
from app_usuarios.models import CustomUser
from app_usuarios.forms import CustomUserCreationForm, EditCustomUserCreationForm
from app_usuarios.tables import UsuarioTable
from django.contrib import messages
from django.contrib.auth.forms import SetPasswordForm
from django.contrib.auth.decorators import login_required

@login_required(login_url='login:login', redirect_field_name='next')
def usuarios_view(request):
    if request.user.is_staff:
        usuarios = CustomUser.objects.all()
    else:
        usuarios = CustomUser.objects.filter(empresa=request.user.empresa)
    table = UsuarioTable(usuarios)
    return render(request, 'pages/usuarios.html', context={
        'title': 'Usuários',
        'table': table
    })

@login_required(login_url='login:login', redirect_field_name='next')
def adicionar_usuario(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request, request.POST)
        if form.is_valid():
            novo_usuario = form.save(commit=False)
            novo_usuario.empresa = form.cleaned_data.get('empresa', request.user.empresa)
            form.save()
            messages.success(request, f'O novo usuário "{novo_usuario.nome}" foi adicionado com sucesso! ')
            return redirect('usuarios:usuarios')
    else:
        form = CustomUserCreationForm(request)
    return render(request, 'pages/adicionar_usuario.html', context={
        'title': 'Adicionar usuário',
        'form': form
    })

@login_required(login_url='login:login', redirect_field_name='next')
def editar_usuario(request, usuario_id):
    usuario = get_object_or_404(CustomUser, pk=usuario_id)
    if request.method == 'POST':
        form = EditCustomUserCreationForm(request.POST, instance=usuario)
        if form.is_valid():
            edit_usuario = form.save()
            messages.success(request, f'O usuário "{edit_usuario.nome}" foi editado com sucesso!')
            return redirect('usuarios:usuarios')
    else:
        form = EditCustomUserCreationForm(instance=usuario)
    return render(request, 'pages/adicionar_usuario.html', context={
        'title': 'Editar usuario',
        'form': form
    })

@login_required(login_url='login:login', redirect_field_name='next')
def editar_senha_usuario(request, usuario_id):
    usuario = CustomUser.objects.get(pk=usuario_id)
    if request.method == 'POST':
        form = SetPasswordForm(user=usuario, data=request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, f'A senha do usuário foi alterada com sucesso!')
            return redirect('usuarios:usuarios')
    else:
        form = SetPasswordForm(user=usuario)
    return render(request, 'pages/adicionar_usuario.html', context={
        'title': f'Editar senha do usuário {CustomUser.nome}',
        'form': form
    })

@login_required(login_url='login:login', redirect_field_name='next')
def deletar_usuario(request, usuario_id):
    usuario = get_object_or_404(CustomUser, pk=usuario_id)

    usuario.delete()
    messages.success(request, f'O usuário foi deletado com sucesso!')
    return redirect('usuarios:usuarios')

app_usuarios/templates/pages/adicionar_usuario.html
{% extends "global/index.html" %}
{% load bootstrap5 %}

{% block content %}
    <a href="{% url "usuarios:usuarios" %}" class="btn btn-primary mb-3">
        <span class="fas fa-arrow-left mr-1"></span>
        Voltar
    </a>
        <div class="card">
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    {% bootstrap_form form %}
                    <button type="submit" class="btn btn-primary">
                        <span class="fas fa-save"></span>
                        Salvar
                    </button>
                </form>
            </div>
        </div>
{% endblock content %}

app_usuarios/templates/pages/botao_acoes_usuarios.html
<div class="dropdown">
    <button class="btn btn-dark btn-sm dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
        Opções
    </button>
    <div class="dropdown-menu">
        <a class="dropdown-item" href="{% url "usuarios:editar_usuario" record.id %}">Editar</a>
        <a class="dropdown-item" href="{% url "usuarios:editar_password" record.id %}">Editar senha</a>
        <a class="dropdown-item" href="{% url "usuarios:deletar_usuario" record.id %}">Deletar</a>
    </div>
</div>

app_usuarios/templates/pages/usuarios.html
{% extends "global/index.html" %}
{% load render_table from django_tables2 %}


{% block content %}
<a href="{% url "usuarios:adicionar_usuario" %}" class="btn btn-primary mb-3">
    <span class="fas fa-plus mr-1"></span>
    Cadastrar
</a>
<div class="card">
    <div class="card-body">
        <table class="table table-bordered table-hover">
            {% render_table table %}
        </table>
    </div>
</div>
{% endblock content %}